function cS2GCUDASingleC_v5c

% CUDA Path
CUDApath = getenv('CUDA_PATH_V11_3');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

mex('-R2018a',...                                       
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA61_DeviceManage_v1c', ... 
    '-lCUDA61_GeneralSM_v1c', ...
    '-lCUDA61_ConvSamp2GridSplitCSM_v1b', ...
    '-lCUDA61_MultiDevMatAddCS_v1a', ...
    '-output','S2GCUDASingleC61_v5c', ...
    'S2GCUDASingleC_v5c.cpp');

mex('-R2018a',...                                       
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA75_DeviceManage_v1c', ... 
    '-lCUDA75_GeneralSM_v1c', ...
    '-lCUDA75_ConvSamp2GridSplitCSM_v1b', ...
    '-lCUDA75_MultiDevMatAddCS_v1a', ...
    '-output','S2GCUDASingleC75_v5c', ...
    'S2GCUDASingleC_v5c.cpp');

mex('-R2018a',...                                       
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA86_DeviceManage_v1c', ... 
    '-lCUDA86_GeneralSM_v1c', ...
    '-lCUDA86_ConvSamp2GridSplitCSM_v1b', ...
    '-lCUDA86_MultiDevMatAddCS_v1a', ...
    '-output','S2GCUDASingleC86_v5c', ...
    'S2GCUDASingleC_v5c.cpp');
