function cS2GCUDADoubleC_v5c

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-largeArrayDims',...                                             % default                            
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_DeviceManage_v1c', ... 
%     '-lCUDA_GeneralDM_v1c', ...
%     '-lCUDA_ConvSamp2GridSplitCDM_v1a', ...
%     '-lCUDA_MultiDevMatAddC_v1a', ...
%     'S2GCUDADoubleC_v5b.cpp');

mex('-R2017b', ...                              % need old API                                                                                      
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_DeviceManage_v1c', ... 
    '-lCUDA_GeneralDM_v1c', ...
    '-lCUDA61_ConvSamp2GridSplitCDM_v1a', ...
    '-lCUDA61_MultiDevMatAddC_v1a', ...
    '-output','S2GCUDADoubleC61_v5c', ...
    'S2GCUDADoubleC_v5c.cpp');

% mex('-R2017b', ...                              % need old API                                   
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_DeviceManage_v1c', ... 
%     '-lCUDA_GeneralDM_v1c', ...
%     '-lCUDA75_ConvSamp2GridSplitCDM_v1a', ...
%     '-lCUDA75_MultiDevMatAddC_v1a', ...
%     '-output','S2GCUDADoubleC75_v5c', ...
%     'S2GCUDADoubleC_v5c.cpp');

