function cS2GCUDADoubleR_v5b

% CUDA Path
CUDApath = getenv('CUDA_PATH');      
CUDApath = [CUDApath,'\lib\x64'];

% CUDA Lib Path
CUDAlib = 'D:\Cuda\zz Library';

% mex('-largeArrayDims',...                                     
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_DeviceManage_v1c', ... 
%     '-lCUDA_GeneralDM_v1c', ...
%     '-lCUDA_ConvSamp2GridSplitRDM_v1a', ...
%     '-lCUDA_MultiDevMatAdd_v1a', ...
%     'S2GCUDADoubleR_v5b.cpp');

% mex('-R2017b', ...                              % need old API                                   
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_DeviceManage_v1c', ... 
%     '-lCUDA_GeneralDM_v1c', ...
%     '-lCUDA61_ConvSamp2GridSplitRDM_v1a', ...
%     '-lCUDA61_MultiDevMatAdd_v1a', ...
%     '-output','S2GCUDADoubleR61_v5b', ...
%     'S2GCUDADoubleR_v5b.cpp');

% mex('-R2017b', ...                              % need old API                                   
%     ['-I',CUDAlib], ...
%     ['-L',CUDApath],'-lcudart', ... 
%     ['-L',CUDAlib], ...
%     '-lCUDA_DeviceManage_v1c', ... 
%     '-lCUDA_GeneralDM_v1c', ...
%     '-lCUDA75_ConvSamp2GridSplitRDM_v1a', ...
%     '-lCUDA75_MultiDevMatAdd_v1a', ...
%     '-output','S2GCUDADoubleR75_v5b', ...
%     'S2GCUDADoubleR_v5b.cpp');

mex('-R2017b', ...                              % need old API                                   
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_DeviceManage_v1c', ... 
    '-lCUDA_GeneralDM_v1c', ...
    '-lCUDA86_ConvSamp2GridSplitRDM_v1a', ...
    '-lCUDA86_MultiDevMatAdd_v1a', ...
    '-output','S2GCUDADoubleR86_v5b', ...
    'S2GCUDADoubleR_v5b.cpp');