function cS2GCUDADoubleR_v5a

% CUDA Path
CUDApath = getenv('CUDA_LIB_PATH');      
%CUDApath = CUDApath(1:end-1);                  % remove last backslash

% CUDA Lib Path
CUDAlib = 'D:\1 Scripts\zy NonMatlabSubRoutines\Set 1.4\CudaSubRoutines\zz Library';

mex('-largeArrayDims',...                                     
    ['-I',CUDAlib], ...
    ['-L',CUDApath],'-lcudart','-lcufft', ... 
    ['-L',CUDAlib], ...
    '-lCUDA_GeneralD_v1b', ...
    '-lCUDA_ConvSamp2GridSplitRD_v1d', ...
    '-lCUDA_DeviceManage_v1b', ... 
    'S2GCUDADoubleR_v5a.cpp');

 % -O = compile with opitmization         library to link with... (the "cudart" library is the CUDA runtime library)